### ISSUE TITLE
tree style tab doesn't show up in new windows by default

### ISSUE THREAD

**Issue by glyh** [MatejKafka/FirefoxTheme#3]
The first firefox window does have tree style tab attached. but whenever I open a new window, I have to  click the tree style tab button to open it.

**Comment by MatejKafka** [comment]
Unfortunately, that behavior is controlled by the browser and I did not find any way to configure it to always open a sidebar in each new window. By default, you can open the TST sidebar by pressing F1, so you can use that instead of clicking the extension button.
